// <auto-generated />
using System;
using EdfUsageDownloader;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EdfUsageDownloader.Migrations
{
    [DbContext(typeof(UsageDbContext))]
    [Migration("20211221140655_Add_Time_Usage_Entity")]
    partial class Add_Time_Usage_Entity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EdfUsageDownloader.DailyUsageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("ElectricityCost")
                        .HasColumnType("double");

                    b.Property<bool>("ElectricityEstimated")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("ElectricityUnits")
                        .HasColumnType("double");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("GasCost")
                        .HasColumnType("double");

                    b.Property<bool>("GasEstimated")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("GasUnits")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("DailyUsage");
                });

            modelBuilder.Entity("EdfUsageDownloader.TimeUsageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("ElectricityUsage")
                        .HasColumnType("double");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("GasUsage")
                        .HasColumnType("double");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TimeUsage");
                });
#pragma warning restore 612, 618
        }
    }
}
